export const CURRICULA = [
  {
    id: 'global', flag: '🌍', country: 'Global / Other',
    hero: 'Your child deserves a tutor who truly understands them',
    subline: 'Expert 1-on-1 sessions for IB, IGCSE, A-Levels & national curricula, online, any timezone.',
    gradeLabel: 'Grade', gradeRange: 'KG-Grade 12',
    exams: ['IB', 'IGCSE', 'A-Levels', 'SAT', 'AP'],
    subjects: ['Mathematics', 'English', 'Science', 'Biology', 'Chemistry', 'Physics', 'Languages', 'Humanities'],
    subjectNote: 'We adapt to any international or national syllabus',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'uk', flag: '🇬🇧', country: 'United Kingdom',
    hero: 'Expert tutors for GCSE & A-Level: results you can measure',
    subline: 'Specialist tutors for Years 1-13 who focus on your child\'s gaps, not a generic lesson plan.',
    gradeLabel: 'Year', gradeRange: 'Year 1-13',
    exams: ['GCSEs', 'A-Levels', 'SATs'],
    subjects: ['Maths', 'English', 'Science', 'History', 'Geography', 'Biology', 'Chemistry', 'Physics', 'French', 'Spanish'],
    subjectNote: null,
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'australia', flag: '🇦🇺', country: 'Australia',
    hero: 'NAPLAN, HSC & VCE prep with tutors who know the curriculum',
    subline: 'Foundation to Year 10 across all 8 learning areas: real progress, not just homework help.',
    gradeLabel: 'Year', gradeRange: 'Foundation-Year 10',
    exams: ['NAPLAN', 'HSC', 'VCE', 'ATAR'],
    subjects: ['Maths', 'English', 'Science', 'HASS', 'Biology', 'Chemistry', 'Physics', 'Digital Technologies'],
    subjectNote: 'Aligned to the Australian Curriculum Version 9.0',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'singapore', flag: '🇸🇬', country: 'Singapore',
    hero: 'PSLE & O-Level specialists who build confidence, not just grades',
    subline: 'Primary 1 to Secondary 5: structured sessions aligned to MOE syllabuses.',
    gradeLabel: 'Primary/Secondary', gradeRange: 'Primary 1-Secondary 5',
    exams: ['PSLE', 'O-Levels', 'N-Levels', 'A-Levels'],
    subjects: ['English', 'Maths', 'Science', 'Mother Tongue', 'Social Studies', 'Additional Maths', 'Combined Science', 'Geography', 'History'],
    subjectNote: 'Aligned to MOE Singapore syllabuses',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'middleeast', flag: '🇦🇪', country: 'UAE / Middle East',
    hero: 'IGCSE, IB & CBSE tutors who match your school\'s syllabus exactly',
    subline: 'KG to Grade 12 across UAE-MoE, American, British & Indian curricula: one platform, every board.',
    gradeLabel: 'Grade', gradeRange: 'KG-Grade 12',
    exams: ['IGCSE', 'A-Levels', 'IB', 'CBSE', 'AP', 'UAE-MoE'],
    subjects: ['Maths', 'English', 'Science', 'Arabic', 'Physics', 'Chemistry', 'Biology', 'Social Studies', 'Islamic Studies'],
    subjectNote: 'Curriculum-agnostic: we map to your school syllabus',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'southafrica', flag: '🇿🇦', country: 'South Africa',
    hero: 'From Grade R to Matric: tutors who know CAPS inside out',
    subline: 'NSC and IEB specialists who close gaps and build exam-ready confidence.',
    gradeLabel: 'Grade', gradeRange: 'Grade R-Grade 12',
    exams: ['Matric', 'NSC', 'IEB'],
    subjects: ['Maths', 'English', 'Physical Sciences', 'Life Sciences', 'Geography', 'History', 'Accounting', 'Business Studies'],
    subjectNote: 'Aligned to the CAPS curriculum',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'us', flag: '🇺🇸', country: 'United States',
    hero: 'Ivy League Caliber SAT, ACT & AP Mentorship',
    subline: 'Elite test prep and GPA management to secure your spot at top US universities.',
    gradeLabel: 'Grade', gradeRange: 'Grade K-12',
    exams: ['SAT', 'ACT', 'AP', 'SSAT', 'ISEE'],
    subjects: ['Math', 'English', 'Science', 'History', 'Calculus AB/BC', 'Physics 1/C', 'Chemistry', 'Biology'],
    subjectNote: 'Aligned to Common Core & College Board standards',
    pricingHint: '3 Free Premium Sessions',
  },
  {
    id: 'test-prep', flag: '🎓', country: 'Test Prep',
    hero: 'Elite Test Preparation for Maximum Scores',
    subline: 'Custom learning pathways for SAT, ACT, AP and more, guided by expert mentors.',
    gradeLabel: 'Grade', gradeRange: 'High School',
    exams: ['SAT', 'ACT', 'AP', '11+', 'BMAT', 'UCAT'],
    subjects: ['Reading', 'Writing', 'Math', 'Science', 'Subject Tests'],
    subjectNote: 'Bespoke test-taking strategies',
    pricingHint: 'Custom Pricing',
  }
]
export const DEFAULT_CURRICULUM = 'global'
